group = 'io.alexrintt.sharedstorage'
version = '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

if (project.findProperty("android.builtInKotlin")?.toString() != "true") {
    apply plugin: "kotlin-android"
}


android {
    namespace = 'io.alexrintt.sharedstorage'
    compileSdk 36

    defaultConfig {
        minSdkVersion 19
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.documentfile:documentfile:1.0.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1"
    implementation "com.anggrayudi:storage:1.3.0"
}
